[project]
name = "td-mcp-server"
version = "0.1.0"
description = "Treasure Data API client for MCP"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.28.0",
    "click>=8.0.0,<8.2.0",
    "pydantic>=2.0.0",
    "mcp[cli]>=1.8.1",
    "typer>=0.9.0",
]

[project.scripts]
mcp = "td_mcp_server.mcp:main"
td-mcp = "td_mcp_server.cli_api:main_td_mcp"
td-list-databases = "td_mcp_server.cli_api:main_list_databases"
td-get-database = "td_mcp_server.cli_api:main_get_database"
td-list-tables = "td_mcp_server.cli_api:main_list_tables"
