[project]
name = "td-mcp-server"
version = "0.1.0"
description = "Treasure Data API client for MCP"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.28.0",
    "click>=8.1.0",
    "pydantic>=2.0.0",
]
